name: Docker push

on:
  push:
    branches: [main]
    
    
jobs:
   deploy:
     runs-on: ubuntu-latest
     
     steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        
      - name: DockerHub Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
          logout: true
        
      - name: Build the docker image
        run: docker build --tag ${{secrets.DOCKER_USERNAME}}/rahul-api . 
        
      - name: tag the image
        run: docker tag ${{secrets.DOCKER_USERNAME}}/rahul-api:latest ${{secrets.DOCKER_USERNAME}}/rahul-api:latest 
      
      - name: Push to Dockerhub
        run: docker push ${{secrets.DOCKER_USERNAME}}/rahul-api
